name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: Aryan181206
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
